### ISSUE TITLE
CarbonTV

### ISSUE THREAD

**Issue by dreamxbmc** [MetalChris/repository.metalchris#11]
"Play from here" creates the play list but the video only plays for 2 seconds before the next video starts.  This repeats for each video on the list.  Only 2 seconds will play before going to next video..

**Comment by MetalChris** [comment]
I'll look into this eventually, but since this is a Kodi feature I rarely, if ever use, it probably won't be any time soon.

**Comment by MetalChris** [comment]
I think the 'Play From Here' function is now fixed.  Let me know if version 0.0.5 works for you.
