### ISSUE TITLE
CW Network Error

### ISSUE THREAD

**Issue by Arkadia2008** [MetalChris/repository.metalchris#12]
I'm getting a CW TV Network Error with the CW Add-on

[]https://paste.ubuntu.com/25626445/

**Comment by MetalChris** [comment]
Yep, you're not the only one.  A fix is in the works.  Was hoping to have it out today, but still a few details to work out.  Should be an update available a day or two.

**Comment by Arkadia2008** [comment]
Working again with v.0.0.2, thanks for your time.

**Comment by MetalChris** [comment]
Closed.
