### ISSUE TITLE
Fox has stopped working again

### ISSUE THREAD

**Issue by Arkadia2008** [MetalChris/repository.metalchris#14]
I'm unable to load the list of Fox TV Shows, they still play from favorites list.

[]https://paste.ubuntu.com/25816150/

**Comment by MetalChris** [comment]
They've made some website changes, again.  I'll look into it this weekend.

**Comment by MetalChris** [comment]
Just uploaded updated version 0.0.9 which should fix the issues.

**Comment by Arkadia2008** [comment]
Working again, thanks.

**Comment by MetalChris** [comment]
Cool.  I'll close the issue.
