### ISSUE TITLE
Add to library (request)

### ISSUE THREAD

**Issue by Arkadia2008** [MetalChris/repository.metalchris#19]
Is it possible to add a library function to Fox and The CW or improve Osmosis (Kodinerds Repo) compatibility?

[]https://github.com/kodinerds/repo

**Comment by MetalChris** [comment]
It's probably possible, but considering this is probably something I would not ever use, and the fact that someone over at Kodinerds has blacklisted my repository with their KN Caretaker dependency, I'm not terribly inclined to work on something like this.  Thanks for the suggestion though.

**Comment by meyerchak** [comment]
https://securitygladiators.com/kn-addon-caretaker/

Your Addons are not illegal. Crazy times. Sorry man. Time to drink some Duff’s. I will write to LibreELEC.
