### ISSUE TITLE
CAA Review

### ISSUE THREAD

**Issue by Lunatixz** [MetalChris/repository.metalchris#20]
**Addon.xml:** https://github.com/MetalChris/repository.metalchris/blob/9d70793d7868406d8b41a3301e28eea189194be8/plugin.video.caa/addon.xml#L4

- Python version should be higher, It doesn't have to be krypton ie 2.25.0 minimum should be 2.20.0.
Also note the wiki addon.xml example, format changes. http://kodi.wiki/view/addon.xml#Dependency_versions

- Simplejson is no longer required dependency "json" is part of the python library.

- Website should point to the plugins sources site, ie www.caa.tv?, its also a good idea to centralize support. Create a kodi forum thread if one doesn't exist and include it in your addon.xml `<forum> `parameter. 

- Plugin Icon should be 512x512 and Fanart should be min. 1280x720.
Also its great to include a few screenshots and add them to the addon.xml.
Below is an example from one of my plugins.
https://github.com/Lunatixz/plugin.video.playonbrowser/blob/master/addon.xml

- Changelog.txt is no longer needed for Jarvis and up.... you can use the addon.xml `<news>` parameter.

- You need to include a LICENSE file that includes your "GPL(v2)" data
https://help.github.com/articles/licensing-a-repository/

**addon.py:**
https://github.com/MetalChris/repository.metalchris/blob/master/plugin.video.caa/addon.py#L8
 Use `import json`

- import os, and use os.path.join to link paths with filenames. ie `os.path.join(artbase,img_key + '.png')`
https://github.com/MetalChris/repository.metalchris/blob/master/plugin.video.caa/addon.py#L59

- It's good practice to use a minimum` xbmc.log` log level of xbmc.LOGDEBUG so that logs don't get flooded with unneeded data.
https://codedocs.xyz/xbmc/xbmc/group__python__xbmc.html#ga3cd3eff2195727144ad6fbabd4744961

- Listitems have changed, you need to use setart and also set a mediatype...
https://github.com/MetalChris/repository.metalchris/blob/master/plugin.video.caa/addon.py#L226
https://github.com/MetalChris/repository.metalchris/blob/master/plugin.video.caa/addon.py#L229
Below is an example from my plugin.
https://github.com/Lunatixz/plugin.video.nbc/blob/master/resources/lib/nbc.py#L204
https://github.com/Lunatixz/plugin.video.nbc/blob/master/resources/lib/nbc.py#L209

- There is also a new skin view helper to set content type.
https://github.com/Lunatixz/plugin.video.nbc/blob/master/resources/lib/nbc.py#L256

- Not a must, but you should consider adding a short cache for website responses... avoid hammering the site?
https://github.com/MetalChris/repository.metalchris/blob/master/plugin.video.caa/addon.py#L177
I prefer the simplecache module, below is an example.
https://github.com/Lunatixz/plugin.video.nbc/blob/master/resources/lib/nbc.py#L80

- Plugins should resolve the urls using internal paths.
change `xbmc.play` and follow my example below.
https://github.com/Lunatixz/plugin.video.nbc/blob/master/resources/lib/nbc.py#L195

**Comment by MetalChris** [comment]
Wow!  That was fast.  Didn't expect you to review it right away.  I think I've addressed all of your points.  Bumped python version to 2.20.0, removed simplejson, icon and fanart are already in compliance, updated the website url, added the <news> tag, and added a LICENSE.txt file.  Didn't add screenshots to the addon.xml, but will probably add some later.  Also, just noticed I still have the requests module as a dependency there, and I'll remove that next update.  Now importing json and os.  Changed loglevel and updated listitem code.  Didn't add any cache, but that sounds like a good idea.  I'll definitely look to add that in future releases, and also some of my other add-ons.  I couldn't get the add-on to work with setResolvedUrl.  I don't know what it is with that, but sometimes it just doesn't work for me.  I'll usually try that first before falling back to xbmc.player, but I've yet to employ that on a consistent basis.  I did get away from using xbmc.player though, and hopefully I've done so in a way that is compliant with the current Kodi standards.

Thanks again for all your help!

**Comment by Lunatixz** [comment]
Great, I'll review the changes... Before you submit we should address url caching.. there are a few options.

XBMC.play is strictly for scripts and probably won't make it into the repository, I'll debug the issue in my end.

**Comment by Lunatixz** [comment]
Hey, sorry I haven't had a chance to debug your play issue... I forked your repository, and hope to have a look this weekend.

**Comment by MetalChris** [comment]
No problem at all.  I did get CAA to play the streams without using xbmc.player, just ended up going a different route than in your example.

**Comment by Lunatixz** [comment]
I must have missed it I do not see setresolver being used... also you need to drop the deprecated variables here. , `iconImage="DefaultFolder.png", thumbnailImage=iconimage)`

**Comment by Lunatixz** [comment]
Hey, FYI repo won't allow using media urls directly linked from the plugin... you need to resolve urls from within the plugin... ie use setresolvedurl. basicly your plugins links should always point inwards to itself, not to an external link... ex. addlink(url='plugin://foo.bar') is okay, addlink(url='http://foobar.com') isn't.

**Comment by MetalChris** [comment]
Yep, I spent some hours after your last comment trying to find more info about setresolvedurl.  There doesn't really seem to be any clear documentation about why it should be used.  After reading through a number of threads in the forum, I finally came across a post by @learningit that spelled it out pretty well.  From my outsider non-coder perspective, this seems like one of those things that is made more complicated than it really needs to be, though I'd imagine there's probably some sound reason behind it.  In any event, between the info you've given me, and the post by @learningit, I think I've got a good idea of what I need to do, and how to do it.  Now I just have to find some time this weekend to get it done.

**Comment by MetalChris** [comment]
Ok, I've implemented setResolvedUrl, finally.  It took a number of attempts to figure out what I was missing, but I finally have it working.  At your suggestion, I've added some screenshots, but after uploading version 2017.11.11, I realized the paths in the addon.xml are incorrect.  I just copied that section of your example addon.xml, but neglected to check the paths before uploading. D'oh!  Anyway, there's only 2 now, and I want to add a few more so I'll fix the addon.xml in the next update, probably tomorrow.

**Comment by Lunatixz** [comment]
Looks better...

**Comment by Lunatixz** [comment]
Hey, did you ever get a chance to finalize those changes you mentioned?

**Comment by MetalChris** [comment]
I believe version 2017.11.12 has all the changes you suggested implemented, except simplecache.  My boss went out on extended leave for surgery mid November so the extra work for me has severely cut into my Kodi time (dammit!).  I still want to try adding it, but it might not happen until next year...  :|
