### ISSUE TITLE
Hunt Channel

### ISSUE THREAD

**Issue by dreamxbmc** [MetalChris/repository.metalchris#21]
I believe there is a url change on Hunt channel live stream.  Live stream gives an error.  On demand works mostly.  Error on recently added section.  All shows section appears to work.

**Comment by MetalChris** [comment]
Updated version 0.1.1 should fix the live stream.  I've removed recently added.  While the feed that provides these videos is still accessible, it does not appear to be populating completely, ie: the links are there, but no titles are provided.  I'll look into adding these back again, if the feed starts working properly again.

Let me know if 0.1.1 fixes the live stream for you.

**Comment by dreamxbmc** [comment]
Still an immediate error on live stream.  And now the on demand isn't working.  Nothing populates.  I will post log later.

**Comment by MetalChris** [comment]
They've made some more major changes to the website.  Most of the resources have moved.  I'm going to wait a few days before I try to make another fix.  No sense fixing it today if they're still in the process of moving things around.  I'll wait until it settles down.

**Comment by MetalChris** [comment]
Just uploaded version 0.1.2, which should fix the issues.

**Comment by MetalChris** [comment]
No issues reported in 30 days, so I'll consider this one solved.
