### ISSUE TITLE
Smithsonian earth not working

### ISSUE THREAD

**Issue by rizayes** [MetalChris/repository.metalchris#24]
Hi crhis,

So, I tried to use smithsonianearth kodi since yesterday, but i cannot seem to watch/open anything. 
I can watch the videos contained in the short documentary. Do you know why?

And, not related, but do you know how can i watch premium lovenature in kodi? Cause i have the subscription also. ( love nature is smithsonian earth for people outside of US)

**Comment by rizayes** [comment]
* I can only watch the videos contained in the short documentary folder

**Comment by MetalChris** [comment]
I had marked this add-on broken sometime ago.  I believe the issue is with the authentication of the login.  I'd like to fix it, but just haven't had time yet.  The content is region-blocked for the U.S. only though.

I do not know if there is an add-on for lovenature.
