### ISSUE TITLE
Hunt Channel Addon

### ISSUE THREAD

**Issue by dreamxbmc** [MetalChris/repository.metalchris#28]
Addon is completely down.  Website was down earlier this week.  After it came back up add-on didn't work.

**Comment by MetalChris** [comment]
Wish they'd tell me before they make changes.  Fortunately, no major changes.  Just uploaded version 0.1.5 which should be fully functional.  Let me know if it works for you.

**Comment by MetalChris** [comment]
Since there are no complaints about version 0.1.5, I'm going to close this.
