### ISSUE TITLE
powernation tv addon

### ISSUE THREAD

**Issue by jwthompson** [MetalChris/repository.metalchris#29]
addon is not working. hopefully can be fixed as its one of my favs. Thanks for your time.

**Comment by MetalChris** [comment]
I was working on it, and got pretty close to having this one fixed, but then my development system crashed.  Took a while to get it back up and running properly again.  Most of the add-on is fixed though I still have some bugs to work out.  Hope to a working version of the add-on uploaded within a week or so.

**Comment by MetalChris** [comment]
Just uploaded new version 2018.04.24 which restores about 95% functionality (YMM & 2 Minute Tech are missing).  Please update and let me know if you experience any issues.

**Comment by jwthompson** [comment]
Thanks for your time, all is good from what i have been checking out.
