### ISSUE TITLE
Update official kodi add-on for the Internet Archive

### ISSUE THREAD

**Issue by petterreinholdtsen** [MetalChris/repository.metalchris#34]
According to https://github.com/divingmule/plugin.audio.internet.archive/issues/1 the Internet Archive add-on is maintained here.  The one in the kodi repositories are currently broken.  Any hope to get a fixed add-in available from the official kodi sources?

**Comment by MetalChris** [comment]
I have no plans to submit my add-ons to the official repository.

**Comment by petterreinholdtsen** [comment]
OK.  Thank you for letting me know.  May I be so brave as to ask why you do not want to submit them to the official repository?
