### ISSUE TITLE
Hunt Channel Live Stream and On Demand Down

### ISSUE THREAD

**Issue by dreamxbmc** [MetalChris/repository.metalchris#35]
Live stream is down and on demand shows names in of shows but no listings.

**Comment by MetalChris** [comment]
Ugh.  More website changes.  Version 0.1.9 should fix the issues.  I don't necessarily have time to fix this every week, and this is the second set of changes in two weeks, so I hope they're done with the changes for a while.

**Comment by dreamxbmc** [comment]
Thanks for the update Chris!
