### ISSUE TITLE
looks like powernation needs fixed again

### ISSUE THREAD

**Issue by jwthompson** [MetalChris/repository.metalchris#38]
[kodi.log](https://github.com/MetalChris/repository.metalchris/files/2422062/kodi.log)

**Comment by MetalChris** [comment]
Some changes to the website, including a change to a paid subscription for the current season.  I'll look into it, but as much as I enjoy the content, I'm not sure it's worth $4.99 per month or even the slightly discounted $49.99 per year.  Past seasons appear to still be available for free, so I'll try to adjust the add-on to only work with those.

**Comment by MetalChris** [comment]
Version 2018.10.03 has been uploaded.  This version will skip over any episodes that require a subscription.  Please give this version a try and let me know if you experience any errors with it.

**Comment by MetalChris** [comment]
No complaints since the update almost two weeks ago.  I'm closing this one.
