### ISSUE TITLE
carbonTV not working

### ISSUE THREAD

**Issue by supmaxi** [MetalChris/repository.metalchris#39]
looks like website changes, addon displays blank menu :(
If you have the time... would be greatly appreciated!

**Comment by MetalChris** [comment]
Yep, lots of changes on the site.  Give me a couple of days and I should have an updated version available.

**Comment by supmaxi** [comment]
awesome, thanks man. legend!

**Comment by supmaxi** [comment]
Auto update came through and working a treat, thanks for your time and assistance, it is greatly appreciated. As for the bad news, i hope not! lol. Thanks again
