### ISSUE TITLE
New cw shows

### ISSUE THREAD

**Issue by R3-D3** [MetalChris/repository.metalchris#42]
Hi
Minor issue as addon still working great. It is not scraping new shows (charmed/legacies)
Thanks

**Comment by MetalChris** [comment]
For some reason, these shows do not show as 'active' in the API, but instead still show as 'coming soon' so the add-on ignores them.  I'll see if I can implement a fix, but I'd rather not have to add exceptions on a show by show basis.

**Comment by MetalChris** [comment]
Three months later, these shows still do not show as 'active' in the API, but rather as 'coming soon' so I'm closing this one since it is actually an issue with the CW API and not an add-on issue.
