### ISSUE TITLE
carbon tv

### ISSUE THREAD

**Issue by ever1234** [MetalChris/repository.metalchris#44]
OK can't login says failed.thanks

**Comment by MetalChris** [comment]
Website changes.  I'll try to take a look at this over the weekend.

**Comment by MetalChris** [comment]
Should be fixed now, let me know if it works for you.  If you're still having issues, please provide a link to a log file.

**Comment by MetalChris** [comment]
Over 10 days and no more complaints, so I'm closing this one.
