### ISSUE TITLE
GSN Icon Suggestion

### ISSUE THREAD

**Issue by CTKISM** [MetalChris/repository.metalchris#49]
The icon for Global Sportsman's Network doesn't have any text, so I added a text layer. Usually, I don't load the wallpapers, just to speed things up a little. Here it is if you want it. 
![icon](https://user-images.githubusercontent.com/44508564/53683833-42e76780-3ccb-11e9-9bf1-9bea99921d3a.png)

**Comment by MetalChris** [comment]
Nice.  I'll add it to the next update.  Thanks!
