### ISSUE TITLE
CW tv network

### ISSUE THREAD

**Issue by buddy9507** [MetalChris/repository.metalchris#51]
Can’t update to 2019.02.16 the CW TV network I have the repo verison 3.3.3 is there a fix?

**Comment by bangheadhere** [comment]
The script is looking for 2019.02.16.zip but that zip is either missing or needs renamed. Currently the only one available is 2019.02.11.zip

**Comment by MetalChris** [comment]
Stupid me.  Forgot to upload the .zip file.  Should be fixed now.

**Comment by buddy9507** [comment]
Ok thank you
