### ISSUE TITLE
plugin.video.space site have changed 

### ISSUE THREAD

**Issue by Sphinxroot** [MetalChris/repository.metalchris#55]
if u you can recode it thank :)

https://www.space.com/

video link now whit many categories
https://videos.space.com/

hls stream 
https://videos-fms.jwpsrv.com/content/conversions/ (random code) /videos/ (random code) .mp4.m3u8 ?token= (random code)

**Comment by MetalChris** [comment]
Thanks for letting me know, I'll take a look at it and see if I can get an update out in the next couple of days.

**Comment by MetalChris** [comment]
Updated version 2020.04.17 has been released.  Tested as fully functional on Linux and Android platforms.  Please let me know if this works for you.

**Comment by Sphinxroot** [comment]
Ty Sir  tested and working good :)
