### ISSUE TITLE
Internet Archive Video: Possible to link to one certain video archive?

### ISSUE THREAD

**Issue by probonopd** [MetalChris/repository.metalchris#56]
Hello, thanks for the Internet Archive Video plugin.

Is it possible to go to
https://archive.org/details/computerchronicles?sort=date
directly and have all episodes listed in chronological order in the plugin?

In case you wonder,

> Hosted by Stewart Cheifet, Computer Chronicles was the world's most popular television program on personal technology during the height of the personal computer revolution. It was broadcast for twenty years from 1983 - 2002. The program was seen on more than 300 television stations in the United States and in over 100 countries worldwide, with translations into French, Spanish, Chinese, and Arabic. The series had a weekly television broadcast audience of over two million viewers.

**Comment by MetalChris** [comment]
Not sure how I missed this notification.  I'm sure it would be possible to go directly to that link.  I've found sorting to be extremely hit and miss on archive.org though.  Unless every single video from this show has the original (and accurate) air date in the description, it would be extremely unlikely to be able sort in chronological order.
