### ISSUE TITLE
CarbonTV

### ISSUE THREAD

**Issue by kizzjay1** [MetalChris/repository.metalchris#8]
Hi! I keep getting an "update failed" message for CarbonTV version  0.0.3. I'm currently running version 0.0.2, & it seems to be working, but it will not update to the new version.

**Comment by MetalChris** [comment]
I look at it over the weekend.  You sure 0.0.2 is working for you?

**Comment by kizzjay1** [comment]
It was when I checked it last night. The first one I tried didn't but then I tried 2 more afterwards & they worked. I haven't tried it today though. Thank u for looking into it!

**Comment by MetalChris** [comment]
Updates have been completed and version 0.0.3 of CarbonTV has now been uploaded.  Let me know if you continue to have any issues.

**Comment by kizzjay1** [comment]
It updated & all is working perfectly! Thank you for your help & quick attention!

**Comment by MetalChris** [comment]
Ok, I'll go ahead and close this one.  Don't hesitate to let me know if you notice any other problems.
