### ISSUE TITLE
Fox Add-on has stopped working

### ISSUE THREAD

**Issue by Arkadia2008** [MetalChris/repository.metalchris#9]
Stopped working about 2 days ago.

https://paste.ubuntu.com/25490542/

**Comment by MetalChris** [comment]
Thanks for letting me know.  Some changes to the website caused the add-on to stop working.  I just uploaded version 0.0.4 which should fix the issues.  Let me know if it works for you.

**Comment by MetalChris** [comment]
Uploaded version 0.0.5 which includes a check to filter out shows that do not have any available episodes.

**Comment by Arkadia2008** [comment]
Working again on Android and Windows with the added bonus of 1080 videos.

Thanks you.

**Comment by Arkadia2008** [comment]
Recently added tv shows are not showing (The Orville, The X-Files).

**Comment by MetalChris** [comment]
Version 0.0.6 should fix the issue.  Some shows (Specials) have been removed (temporarily) since the API for these functions differently.  I hope to eventually add these back.

**Comment by MetalChris** [comment]
Oops, version 0.0.6 had a broken line of code.  Version 0.0.7 should be working.

**Comment by Arkadia2008** [comment]
Works fine now, thanks.

**Comment by MetalChris** [comment]
Ok, closing this issue.  Thanks for the feedback.
